# Project Information
site_name: PagerDuty Full-Service Ownership Documentation
site_description: A collection of best practices for empowering engineers to own their code and services in production. This guide teaches you how to develop the right culture to implement full-service owenrship strategies, and how to foster an environment of accountability with high quality code.
site_author: PagerDuty, Inc.
site_favicon: 'assets/img/favicon.png'
site_url: https://fullserviceownership.pagerduty.com

# Repository
repo_url: https://github.com/PagerDuty/full-service-ownership-docs

# Copyright
copyright: 'Copyright &copy; PagerDuty, Inc.'

# Theme
theme: 'material'
theme_dir: 'theme'
extra_css: ['assets/css/pagerduty.css','assets/css/custom.css']
extra_javascript: ['js/github_forks.js']
extra:
  favicon: 'assets/img/favicon.png'
  logo: 'assets/img/icon.png'
  cover: 'assets/img/covers/default.png'
  palette:
    primary: 'green'
    accent: 'blue grey'
  author:
    github: 'PagerDuty'
    twitter: 'PagerDuty'

# Dev URL
dev_addr: '0.0.0.0:8080'

# Contents
pages:
  - Home: 'index.md'
  - Definitions: 'definitions.md'
  - Digital Transformation: 'digital_transformation.md'
  - Implementing Full-Service Ownership: 'implementing_full_service_ownership_model.md'
  - Getting Tactical - How to go On-Call: 'getting_tactical.md'
  - After On-Call: 'after.md'
  - Additional Resources: 'resources.md'

# Analytics
google_analytics: ['UA-8759953-1', 'auto']

# Extensions
markdown_extensions:
  - toc:
      permalink: '#'
  - sane_lists:
  - admonition:
  - meta:
  - pymdownx.details:
  - pymdownx.extra:
  - pymdownx.mark:
  - pymdownx.tilde:
