# Project Information
site_name: PagerDuty Full-Service Ownership Documentation
site_description: A collection of best practices for empowering engineers to own their code and services in production. This guide provides a step-by-step process to help teams implement and scale full-service ownership methodology across their organization.
site_author: PagerDuty, Inc.
site_url: https://ownership.pagerduty.com/

# Repository
repo_url: https://github.com/PagerDuty/full-service-ownership-docs

# Copyright
copyright: 'Copyright &copy; PagerDuty, Inc.'

# Theme
theme:
  name: pagerduty
  title: 'Full Service Ownership'

# Contents
nav:
  - Home: 'index.md'
  - Introduction: 'introduction.md'
  - Digital Transformation: 'digital_transformation.md'
  - Defining a Service: 'defining.md'
  - Service Ownership Functions: 'functions.md'
  - Lifecycle of a Service: 'lifecycle.md'
  - Escalation Policies: 'escalations.md'
  - On-Call Shifts: 'on-call.md'
  - Tips for Getting Started: 'getting_started.md'
  - Tips for Scaling: 'scaling.md'
  - Next Steps: 'next_steps.md'
  - Additional Resources: 'resources.md'

# Analytics
google_analytics: ['UA-8759953-1', 'auto']

# Extensions
markdown_extensions:
  - toc:
      permalink: '#'
  - sane_lists:
  - admonition:
  - meta:
  - pymdownx.details:
  - pymdownx.extra:
  - pymdownx.mark:
  - pymdownx.tilde:
  - pymdownx.highlight:
  - pymdownx.superfences:
  - pymdownx.tabbed:

# Development URL, bind to local only.
dev_addr: '127.0.0.1:8000'
