[[headers]]
  for = "/*"
  [headers.values]
    Strict-Transport-Security = "max-age=31536000 ; includeSubDomains"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "same-origin"
    Feature-Policy = "accelerometer 'none'; camera 'none'; geolocation 'none'; gyroscope 'none'; magnetometer 'none'; microphone 'none'; payment 'none'; usb 'none'"
    Content-Security-Policy-Report-Only = "default-src 'none'; script-src 'self' ssl.google-analytics.com www.google-analytics.com 'sha256-toUGKjz52dsxW3Ss9A0+0V2FTyXDdzyz29y+nkTlBH4=' 'sha256-dvEGALffsKZkQDCGfK1s8jBRcomc5RSvZ3xhaBuggKk=' 'sha256-fX9qfHwuLRAhhgRM/UaGciy4GcC8DMLAacNFMsVHnk8=' 'sha256-VjLSDWC2yf+fPNjXC2iYDfASyKbLaL6IiCdBMPzjj+E='; object-src 'self'; style-src 'self' 'sha256-LpfmXS+4ZtL2uPRZgkoR29Ghbxcfime/CsD/4w5VujE=' 'sha256-nK6A3vwzvwoN92MnHZrWtylYkYmW1jCQgTqWKQJNBMI=' 'sha256-QVPYhFew7P3p46DxC68MMy/iAdzPaXWHAFcS3O2A0tI='; img-src 'self' data: ssl.google-analytics.com www.google-analytics.com; media-src 'none'; frame-src 'none'; font-src 'self'; connect-src 'self' api.github.com; base-uri 'none'; form-action 'self'; frame-ancestors 'none'"

